# Generated by Django 5.2.4 on 2025-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_info',
            field=models.TextField(blank=True, verbose_name='Информация об авторе'),
        ),
    ]
