# Generated by Django 5.2.4 on 2025-07-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bookrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на интервью')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на статью')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на тренд')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Тренд',
                'verbose_name_plural': 'Тренды',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на обновление')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Обновление',
                'verbose_name_plural': 'Обновления',
            },
        ),
        migrations.CreateModel(
            name='BookOfTheYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на статью')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.book', verbose_name='Книга года')),
            ],
            options={
                'verbose_name': 'Самая читаемая книга года',
                'verbose_name_plural': 'Самые читаемые книги года',
            },
        ),
    ]
