# Generated by Django 5.2.4 on 2025-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_interview_news_trend_update_bookoftheyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='trends/', verbose_name='Превью (картинка)'),
        ),
    ]
