# Generated by Django 5.2.4 on 2025-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_trend_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookoftheyear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_of_year/', verbose_name='Фото (обложка/иллюстрация)'),
        ),
    ]
